IFDEF RAX
ELSE
	.MODEL flat, C
ENDIF

WrapFunction MACRO functionName

IFDEF RAX
	EXTERN @CatStr( original,  functionName): QWORD
ELSE
	EXTERN @CatStr( original,  functionName): DWORD
ENDIF

@CatStr( _, functionName ) PROC
jmp [ @CatStr( original,  functionName) ]
@CatStr( _, functionName ) ENDP

ENDM

_DATA SEGMENT
_DATA ENDS
_TEXT SEGMENT

WrapFunction CreateDirect3D11DeviceFromDXGIDevice
WrapFunction CreateDirect3D11SurfaceFromDXGISurface
WrapFunction D3D11CoreCreateDevice
WrapFunction D3D11CoreCreateLayeredDevice
WrapFunction D3D11CoreGetLayeredDeviceSize
WrapFunction D3D11CoreRegisterLayers
WrapFunction D3D11CreateDevice
WrapFunction D3D11CreateDeviceAndSwapChain
WrapFunction D3D11CreateDeviceForD3D12
WrapFunction D3D11On12CreateDevice
WrapFunction D3DKMTCloseAdapter
WrapFunction D3DKMTCreateAllocation
WrapFunction D3DKMTCreateContext
WrapFunction D3DKMTCreateDevice
WrapFunction D3DKMTCreateSynchronizationObject
WrapFunction D3DKMTDestroyAllocation
WrapFunction D3DKMTDestroyContext
WrapFunction D3DKMTDestroyDevice
WrapFunction D3DKMTDestroySynchronizationObject
WrapFunction D3DKMTEscape
WrapFunction D3DKMTGetContextSchedulingPriority
WrapFunction D3DKMTGetDeviceState
WrapFunction D3DKMTGetDisplayModeList
WrapFunction D3DKMTGetMultisampleMethodList
WrapFunction D3DKMTGetRuntimeData
WrapFunction D3DKMTGetSharedPrimaryHandle
WrapFunction D3DKMTLock
WrapFunction D3DKMTOpenAdapterFromHdc
WrapFunction D3DKMTOpenResource
WrapFunction D3DKMTPresent
WrapFunction D3DKMTQueryAdapterInfo
WrapFunction D3DKMTQueryAllocationResidency
WrapFunction D3DKMTQueryResourceInfo
WrapFunction D3DKMTRender
WrapFunction D3DKMTSetAllocationPriority
WrapFunction D3DKMTSetContextSchedulingPriority
WrapFunction D3DKMTSetDisplayMode
WrapFunction D3DKMTSetDisplayPrivateDriverFormat
WrapFunction D3DKMTSetGammaRamp
WrapFunction D3DKMTSetVidPnSourceOwner
WrapFunction D3DKMTSignalSynchronizationObject
WrapFunction D3DKMTUnlock
WrapFunction D3DKMTWaitForSynchronizationObject
WrapFunction D3DKMTWaitForVerticalBlankEvent
WrapFunction D3DPerformance_BeginEvent
WrapFunction D3DPerformance_EndEvent
WrapFunction D3DPerformance_GetStatus
WrapFunction D3DPerformance_SetMarker
WrapFunction EnableFeatureLevelUpgrade
WrapFunction OpenAdapter10
WrapFunction OpenAdapter10_2

WrapFunction XInputGetState
WrapFunction XInputSetState
WrapFunction XInputGetCapabilities
WrapFunction XInputEnable
WrapFunction XInputGetDSoundAudioDeviceGuids
WrapFunction XInputGetBatteryInformation
WrapFunction XInputGetKeystroke
WrapFunction XInputGetStateEx
WrapFunction XInputWaitForGuideButton
WrapFunction XInputCancelGuideButtonWait
WrapFunction XInputPowerOffController

WrapFunction Direct3DShaderValidatorCreate9
WrapFunction PSGPError
WrapFunction PSGPSampleTexture
WrapFunction D3DPERF_BeginEvent
WrapFunction D3DPERF_EndEvent
WrapFunction D3DPERF_GetStatus
WrapFunction D3DPERF_QueryRepeatFrame
WrapFunction D3DPERF_SetMarker
WrapFunction D3DPERF_SetOptions
WrapFunction D3DPERF_SetRegion
WrapFunction DebugSetLevel
WrapFunction DebugSetMute
WrapFunction Direct3D9EnableMaximizedWindowedModeShim
WrapFunction Direct3DCreate9
WrapFunction Direct3DCreate9Ex

WrapFunction wglUseFontOutlinesA
WrapFunction wglUseFontOutlinesW
WrapFunction wglDescribeLayerPlane
WrapFunction wglSetLayerPaletteEntries
WrapFunction wglGetLayerPaletteEntries
WrapFunction wglRealizeLayerPalette
WrapFunction wglSwapLayerBuffers
WrapFunction wglMakeCurrent
WrapFunction GlmfInitPlayback
WrapFunction GlmfBeginGlsBlock
WrapFunction GlmfPlayGlsRecord
WrapFunction GlmfEndGlsBlock
WrapFunction GlmfEndPlayback
WrapFunction GlmfCloseMetaFile
WrapFunction wglSwapMultipleBuffers
WrapFunction wglCreateLayerContext
WrapFunction wglCreateContext
WrapFunction wglDeleteContext
WrapFunction wglGetCurrentContext
WrapFunction wglGetCurrentDC
WrapFunction wglUseFontBitmapsA
WrapFunction wglUseFontBitmapsW
WrapFunction wglShareLists
WrapFunction wglGetDefaultProcAddress
WrapFunction wglGetProcAddress
WrapFunction wglCopyContext
WrapFunction glDebugEntry
WrapFunction wglGetPixelFormat
WrapFunction wglSetPixelFormat
WrapFunction wglChoosePixelFormat	
WrapFunction wglDescribePixelFormat
WrapFunction wglSwapBuffers
WrapFunction glCallList
WrapFunction glCallLists
WrapFunction glBegin
WrapFunction glColor3b
WrapFunction glColor3bv
WrapFunction glColor3d
WrapFunction glColor3dv
WrapFunction glColor3f
WrapFunction glColor3fv
WrapFunction glColor3i
WrapFunction glColor3iv
WrapFunction glColor3s
WrapFunction glColor3sv
WrapFunction glColor3ub
WrapFunction glColor3ubv
WrapFunction glColor3ui
WrapFunction glColor3uiv
WrapFunction glColor3us
WrapFunction glColor3usv
WrapFunction glColor4b
WrapFunction glColor4bv
WrapFunction glColor4d
WrapFunction glColor4dv
WrapFunction glColor4f
WrapFunction glColor4fv
WrapFunction glColor4i
WrapFunction glColor4iv
WrapFunction glColor4s
WrapFunction glColor4sv
WrapFunction glColor4ub
WrapFunction glColor4ubv
WrapFunction glColor4ui
WrapFunction glColor4uiv
WrapFunction glColor4us
WrapFunction glColor4usv
WrapFunction glEdgeFlag
WrapFunction glEdgeFlagv
WrapFunction glEnd
WrapFunction glIndexd
WrapFunction glIndexdv
WrapFunction glIndexf
WrapFunction glIndexfv
WrapFunction glIndexi
WrapFunction glIndexiv
WrapFunction glIndexs
WrapFunction glIndexsv
WrapFunction glNormal3b
WrapFunction glNormal3bv
WrapFunction glNormal3d
WrapFunction glNormal3dv
WrapFunction glNormal3f
WrapFunction glNormal3fv
WrapFunction glNormal3i
WrapFunction glNormal3iv
WrapFunction glNormal3s
WrapFunction glNormal3sv
WrapFunction glTexCoord1d
WrapFunction glTexCoord1dv
WrapFunction glTexCoord1f
WrapFunction glTexCoord1fv
WrapFunction glTexCoord1i
WrapFunction glTexCoord1iv
WrapFunction glTexCoord1s
WrapFunction glTexCoord1sv
WrapFunction glTexCoord2d
WrapFunction glTexCoord2dv
WrapFunction glTexCoord2f
WrapFunction glTexCoord2fv
WrapFunction glTexCoord2i
WrapFunction glTexCoord2iv
WrapFunction glTexCoord2s
WrapFunction glTexCoord2sv
WrapFunction glTexCoord3d
WrapFunction glTexCoord3dv
WrapFunction glTexCoord3f
WrapFunction glTexCoord3fv
WrapFunction glTexCoord3i
WrapFunction glTexCoord3iv
WrapFunction glTexCoord3s
WrapFunction glTexCoord3sv
WrapFunction glTexCoord4d
WrapFunction glTexCoord4dv
WrapFunction glTexCoord4f
WrapFunction glTexCoord4fv
WrapFunction glTexCoord4i
WrapFunction glTexCoord4iv
WrapFunction glTexCoord4s
WrapFunction glTexCoord4sv
WrapFunction glVertex2d
WrapFunction glVertex2dv
WrapFunction glVertex2f
WrapFunction glVertex2fv
WrapFunction glVertex2i
WrapFunction glVertex2iv
WrapFunction glVertex2s
WrapFunction glVertex2sv
WrapFunction glVertex3d
WrapFunction glVertex3dv
WrapFunction glVertex3f
WrapFunction glVertex3fv
WrapFunction glVertex3i
WrapFunction glVertex3iv
WrapFunction glVertex3s
WrapFunction glVertex3sv
WrapFunction glVertex4d
WrapFunction glVertex4dv
WrapFunction glVertex4f
WrapFunction glVertex4fv
WrapFunction glVertex4i
WrapFunction glVertex4iv
WrapFunction glVertex4s
WrapFunction glVertex4sv
WrapFunction glMaterialf
WrapFunction glMaterialfv
WrapFunction glMateriali
WrapFunction glMaterialiv
WrapFunction glDisable
WrapFunction glEnable
WrapFunction glPopAttrib
WrapFunction glPushAttrib
WrapFunction glEvalCoord1d
WrapFunction glEvalCoord1dv
WrapFunction glEvalCoord1f
WrapFunction glEvalCoord1fv
WrapFunction glEvalCoord2d
WrapFunction glEvalCoord2dv
WrapFunction glEvalCoord2f
WrapFunction glEvalCoord2fv
WrapFunction glEvalPoint1
WrapFunction glEvalPoint2
WrapFunction glLoadIdentity
WrapFunction glLoadMatrixf
WrapFunction glLoadMatrixd
WrapFunction glMatrixMode
WrapFunction glMultMatrixf
WrapFunction glMultMatrixd
WrapFunction glPopMatrix
WrapFunction glPushMatrix
WrapFunction glRotated
WrapFunction glRotatef
WrapFunction glScaled
WrapFunction glScalef
WrapFunction glTranslated
WrapFunction glTranslatef
WrapFunction glArrayElement
WrapFunction glBindTexture
WrapFunction glColorPointer
WrapFunction glDisableClientState
WrapFunction glDrawArrays
WrapFunction glDrawElements
WrapFunction glEdgeFlagPointer
WrapFunction glEnableClientState
WrapFunction glIndexPointer
WrapFunction glIndexub
WrapFunction glIndexubv
WrapFunction glInterleavedArrays
WrapFunction glNormalPointer
WrapFunction glPolygonOffset
WrapFunction glTexCoordPointer
WrapFunction glVertexPointer
WrapFunction glGetPointerv
WrapFunction glPopClientAttrib
WrapFunction glPushClientAttrib
WrapFunction glClear
WrapFunction glClearAccum
WrapFunction glClearIndex
WrapFunction glClearColor
WrapFunction glClearStencil
WrapFunction glClearDepth
WrapFunction glBitmap
WrapFunction glTexImage1D
WrapFunction glTexImage2D
WrapFunction glCopyPixels
WrapFunction glReadPixels
WrapFunction glDrawPixels
WrapFunction glRectd
WrapFunction glRectdv
WrapFunction glRectf
WrapFunction glRectfv
WrapFunction glRecti
WrapFunction glRectiv
WrapFunction glRects
WrapFunction glRectsv
WrapFunction glEndList
WrapFunction glDeleteLists
WrapFunction glGenLists
WrapFunction glListBase
WrapFunction glRasterPos2d
WrapFunction glRasterPos2dv
WrapFunction glRasterPos2f
WrapFunction glRasterPos2fv
WrapFunction glRasterPos2i
WrapFunction glRasterPos2iv
WrapFunction glRasterPos2s
WrapFunction glRasterPos2sv
WrapFunction glRasterPos3d
WrapFunction glRasterPos3dv
WrapFunction glRasterPos3f
WrapFunction glRasterPos3fv
WrapFunction glRasterPos3i
WrapFunction glRasterPos3iv
WrapFunction glRasterPos3s
WrapFunction glRasterPos3sv
WrapFunction glRasterPos4d
WrapFunction glRasterPos4dv
WrapFunction glRasterPos4f
WrapFunction glRasterPos4fv
WrapFunction glRasterPos4i
WrapFunction glRasterPos4iv
WrapFunction glRasterPos4s
WrapFunction glRasterPos4sv
WrapFunction glClipPlane
WrapFunction glColorMaterial
WrapFunction glCullFace
WrapFunction glFogf
WrapFunction glFogfv
WrapFunction glFogi
WrapFunction glFogiv
WrapFunction glFrontFace
WrapFunction glHint
WrapFunction glLightf
WrapFunction glLightfv
WrapFunction glLighti
WrapFunction glLightiv
WrapFunction glLightModelf
WrapFunction glLightModelfv
WrapFunction glLightModeli
WrapFunction glLightModeliv
WrapFunction glLineStipple
WrapFunction glLineWidth
WrapFunction glPointSize
WrapFunction glPolygonMode
WrapFunction glPolygonStipple
WrapFunction glFinish
WrapFunction glShadeModel
WrapFunction glTexParameterf
WrapFunction glTexParameterfv
WrapFunction glTexParameteri
WrapFunction glTexParameteriv
WrapFunction glTexEnvf
WrapFunction glTexEnvfv
WrapFunction glTexEnvi
WrapFunction glTexEnviv
WrapFunction glTexGend
WrapFunction glTexGendv
WrapFunction glTexGenf
WrapFunction glTexGenfv
WrapFunction glTexGeni
WrapFunction glTexGeniv
WrapFunction glFeedbackBuffer	
WrapFunction glSelectBuffer
WrapFunction glRenderMode
WrapFunction glInitNames
WrapFunction glLoadName
WrapFunction glPassThrough
WrapFunction glPopName
WrapFunction glPushName
WrapFunction glDrawBuffer
WrapFunction glStencilMask
WrapFunction glColorMask
WrapFunction glDepthMask
WrapFunction glIndexMask
WrapFunction glScissor
WrapFunction glNewList
WrapFunction glAccum
WrapFunction glFlush
WrapFunction glMap1d
WrapFunction glMap1f
WrapFunction glMap2d
WrapFunction glMap2f
WrapFunction glMapGrid1d
WrapFunction glMapGrid1f
WrapFunction glMapGrid2d
WrapFunction glMapGrid2f
WrapFunction glEvalMesh1
WrapFunction glEvalMesh2
WrapFunction glAlphaFunc
WrapFunction glBlendFunc
WrapFunction glLogicOp
WrapFunction glStencilFunc
WrapFunction glStencilOp
WrapFunction glDepthFunc
WrapFunction glPixelZoom
WrapFunction glPixelTransferf
WrapFunction glPixelTransferi
WrapFunction glPixelStoref
WrapFunction glPixelStorei
WrapFunction glPixelMapfv
WrapFunction glPixelMapuiv
WrapFunction glPixelMapusv
WrapFunction glReadBuffer
WrapFunction glGetBooleanv
WrapFunction glGetClipPlane
WrapFunction glGetDoublev
WrapFunction glGetError
WrapFunction glGetFloatv
WrapFunction glGetIntegerv
WrapFunction glGetLightfv
WrapFunction glGetLightiv
WrapFunction glGetMapdv
WrapFunction glGetMapfv
WrapFunction glGetMapiv
WrapFunction glGetMaterialfv
WrapFunction glGetMaterialiv
WrapFunction glGetPixelMapfv
WrapFunction glGetPixelMapuiv
WrapFunction glGetPixelMapusv
WrapFunction glGetPolygonStipple
WrapFunction glGetString
WrapFunction glGetTexEnvfv
WrapFunction glGetTexEnviv
WrapFunction glGetTexGendv
WrapFunction glGetTexGenfv
WrapFunction glGetTexGeniv
WrapFunction glGetTexImage
WrapFunction glGetTexParameterfv
WrapFunction glGetTexParameteriv
WrapFunction glGetTexLevelParameterfv
WrapFunction glGetTexLevelParameteriv
WrapFunction glIsEnabled
WrapFunction glIsList
WrapFunction glDepthRange
WrapFunction glFrustum
WrapFunction glOrtho
WrapFunction glViewport
WrapFunction glAreTexturesResident
WrapFunction glCopyTexImage1D
WrapFunction glCopyTexImage2D
WrapFunction glCopyTexSubImage1D
WrapFunction glCopyTexSubImage2D
WrapFunction glDeleteTextures
WrapFunction glGenTextures
WrapFunction glIsTexture
WrapFunction glPrioritizeTextures
WrapFunction glTexSubImage1D
WrapFunction glTexSubImage2D

WrapFunction PlaySoundW                                                                       
WrapFunction timeSetEvent                                                                     
WrapFunction timeKillEvent                                                                    
WrapFunction midiOutMessage                                                                   
WrapFunction timeBeginPeriod                                                                  
WrapFunction timeGetTime                                                                      
WrapFunction NotifyCallbackData                                                               
WrapFunction WOW32DriverCallback                                                              
WrapFunction WOW32ResolveMultiMediaHandle                                                     
WrapFunction aux32Message                                                                     
WrapFunction joy32Message                                                                     
WrapFunction mid32Message                                                                     
WrapFunction mod32Message                                                                     
WrapFunction mxd32Message                                                                     
WrapFunction tid32Message                                                                     
WrapFunction wid32Message                                                                     
WrapFunction wod32Message                                                                     
WrapFunction mci32Message                                                                     
WrapFunction CloseDriver                                                                      
WrapFunction DefDriverProc                                                                    
WrapFunction DriverCallback                                                                   
WrapFunction DrvGetModuleHandle                                                               
WrapFunction GetDriverModuleHandle                                                            
WrapFunction OpenDriver                                                                       
WrapFunction PlaySound                                                                        
WrapFunction Ordinal2                                                                         
WrapFunction SendDriverMessage                                                                
WrapFunction auxGetDevCapsA                                                                   
WrapFunction auxGetDevCapsW                                                                   
WrapFunction auxGetNumDevs                                                                    
WrapFunction auxGetVolume                                                                     
WrapFunction auxOutMessage                                                                    
WrapFunction auxSetVolume                                                                     
WrapFunction joyConfigChanged                                                                 
WrapFunction joyGetDevCapsA                                                                   
WrapFunction joyGetDevCapsW                                                                   
WrapFunction joyGetNumDevs                                                                    
WrapFunction joyGetPosEx                                                                      
WrapFunction joyGetPos                                                                        
WrapFunction joyGetThreshold                                                                  
WrapFunction joyReleaseCapture                                                                
WrapFunction joySetCapture                                                                    
WrapFunction joySetThreshold                                                                  
WrapFunction midiConnect                                                                      
WrapFunction midiDisconnect                                                                   
WrapFunction midiInAddBuffer                                                                  
WrapFunction midiInClose                                                                      
WrapFunction midiInGetDevCapsA                                                                
WrapFunction midiInGetDevCapsW                                                                
WrapFunction midiInGetErrorTextA                                                              
WrapFunction midiInGetErrorTextW                                                              
WrapFunction midiInGetID                                                                      
WrapFunction midiInGetNumDevs                                                                 
WrapFunction midiInMessage                                                                    
WrapFunction midiInOpen                                                                       
WrapFunction midiInPrepareHeader                                                              
WrapFunction midiInReset                                                                      
WrapFunction midiInStart                                                                      
WrapFunction midiInStop                                                                       
WrapFunction midiInUnprepareHeader                                                            
WrapFunction midiOutCacheDrumPatches                                                          
WrapFunction midiOutCachePatches                                                              
WrapFunction midiOutClose                                                                     
WrapFunction midiOutGetDevCapsA                                                               
WrapFunction midiOutGetDevCapsW                                                               
WrapFunction midiOutGetErrorTextA                                                             
WrapFunction midiOutGetErrorTextW                                                             
WrapFunction midiOutGetID                                                                     
WrapFunction midiOutGetNumDevs                                                                
WrapFunction midiOutGetVolume                                                                 
WrapFunction midiOutLongMsg                                                                   
WrapFunction midiOutOpen                                                                      
WrapFunction midiOutPrepareHeader                                                             
WrapFunction midiOutReset                                                                     
WrapFunction midiOutSetVolume                                                                 
WrapFunction midiOutShortMsg                                                                  
WrapFunction midiOutUnprepareHeader                                                           
WrapFunction midiStreamClose                                                                  
WrapFunction midiStreamOpen                                                                   
WrapFunction midiStreamOut                                                                    
WrapFunction midiStreamPause                                                                  
WrapFunction midiStreamPosition                                                               
WrapFunction midiStreamProperty                                                               
WrapFunction midiStreamRestart                                                                
WrapFunction midiStreamStop                                                                   
WrapFunction mixerClose                                                                       
WrapFunction mixerGetControlDetailsA                                                          
WrapFunction mixerGetControlDetailsW                                                          
WrapFunction mixerGetDevCapsA                                                                 
WrapFunction mixerGetDevCapsW                                                                 
WrapFunction mixerGetID                                                                       
WrapFunction mixerGetLineControlsA                                                            
WrapFunction mixerGetLineControlsW                                                            
WrapFunction mixerGetLineInfoA                                                                
WrapFunction mixerGetLineInfoW                                                                
WrapFunction mixerGetNumDevs                                                                  
WrapFunction mixerMessage                                                                     
WrapFunction mixerOpen                                                                        
WrapFunction mixerSetControlDetails                                                           
WrapFunction mmDrvInstall                                                                     
WrapFunction mmGetCurrentTask                                                                 
WrapFunction mmTaskBlock                                                                      
WrapFunction mmTaskCreate                                                                     
WrapFunction mmTaskSignal                                                                     
WrapFunction mmTaskYield                                                                      
WrapFunction mmioAdvance                                                                      
WrapFunction mmioAscend                                                                       
WrapFunction mmioClose                                                                        
WrapFunction mmioCreateChunk                                                                  
WrapFunction mmioDescend                                                                      
WrapFunction mmioFlush                                                                        
WrapFunction mmioGetInfo                                                                      
WrapFunction mmioInstallIOProcA                                                               
WrapFunction mmioInstallIOProcW                                                               
WrapFunction mmioOpenA                                                                        
WrapFunction mmioOpenW                                                                        
WrapFunction mmioRead                                                                         
WrapFunction mmioRenameA                                                                      
WrapFunction mmioRenameW                                                                      
WrapFunction mmioSeek                                                                         
WrapFunction mmioSendMessage                                                                  
WrapFunction mmioSetBuffer                                                                    
WrapFunction mmioSetInfo                                                                      
WrapFunction mmioStringToFOURCCA                                                              
WrapFunction mmioStringToFOURCCW                                                              
WrapFunction mmioWrite                                                                        
WrapFunction timeEndPeriod                                                                    
WrapFunction timeGetDevCaps                                                                   
WrapFunction timeGetSystemTime                                                                
WrapFunction waveInAddBuffer                                                                  
WrapFunction waveInClose                                                                      
WrapFunction waveInGetDevCapsA                                                                
WrapFunction waveInGetDevCapsW                                                                
WrapFunction waveInGetErrorTextA                                                              
WrapFunction waveInGetErrorTextW                                                              
WrapFunction waveInGetID                                                                      
WrapFunction waveInGetNumDevs                                                                 
WrapFunction waveInGetPosition                                                                
WrapFunction waveInMessage                                                                    
WrapFunction waveInOpen                                                                       
WrapFunction waveInPrepareHeader                                                              
WrapFunction waveInReset                                                                      
WrapFunction waveInStart                                                                      
WrapFunction waveInStop                                                                       
WrapFunction waveInUnprepareHeader                                                            
WrapFunction waveOutBreakLoop                                                                 
WrapFunction waveOutClose                                                                     
WrapFunction waveOutGetDevCapsA                                                               
WrapFunction waveOutGetDevCapsW                                                               
WrapFunction waveOutGetErrorTextA                                                             
WrapFunction waveOutGetErrorTextW                                                             
WrapFunction waveOutGetID                                                                     
WrapFunction waveOutGetNumDevs                                                                
WrapFunction waveOutGetPitch                                                                  
WrapFunction waveOutGetPlaybackRate                                                           
WrapFunction waveOutGetPosition                                                               
WrapFunction waveOutGetVolume                                                                 
WrapFunction waveOutMessage                                                                   
WrapFunction waveOutOpen                                                                      
WrapFunction waveOutPause                                                                     
WrapFunction waveOutPrepareHeader                                                             
WrapFunction waveOutReset                                                                     
WrapFunction waveOutRestart                                                                   
WrapFunction waveOutSetPitch                                                                  
WrapFunction waveOutSetPlaybackRate                                                           
WrapFunction waveOutSetVolume                                                                 
WrapFunction waveOutUnprepareHeader                                                           
WrapFunction waveOutWrite                                                                     
WrapFunction mciExecute                                                                       
WrapFunction mciGetErrorStringA                                                               
WrapFunction mciGetErrorStringW                                                               
WrapFunction mciSendCommandA                                                                  
WrapFunction mciSendCommandW                                                                  
WrapFunction mciSendStringA                                                                   
WrapFunction mciSendStringW                                                                   
WrapFunction mciFreeCommandResource                                                           
WrapFunction mciLoadCommandResource                                                           
WrapFunction mciDriverNotify                                                                  
WrapFunction mciDriverYield                                                                   
WrapFunction mciGetCreatorTask                                                                
WrapFunction mciGetDeviceIDA                                                                  
WrapFunction mciGetDeviceIDFromElementIDA                                                     
WrapFunction mciGetDeviceIDFromElementIDW                                                     
WrapFunction mciGetDeviceIDW                                                                  
WrapFunction mciGetDriverData                                                                 
WrapFunction mciGetYieldProc                                                                  
WrapFunction mciSetDriverData                                                                 
WrapFunction mciSetYieldProc                                                                  
WrapFunction PlaySoundA                                                                       
WrapFunction sndPlaySoundA                                                                    
WrapFunction sndPlaySoundW                                                                    
WrapFunction WOWAppExit                                                                  
WrapFunction mmsystemGetVersion

_TEXT ENDS
END
